# Generated by Django 5.2.8 on 2025-12-31 05:16

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=cloudinary.models.CloudinaryField(default='profile_pics/default', max_length=255, verbose_name='image'),
        ),
    ]
